### ISSUE TITLE
Force https redirect for each charm integrated with Traefik

### ISSUE THREAD

**Issue by baycarbone** [canonical/cos-lite-bundle#114]
### Enhancement Proposal

When choosing to enable TLS for communication flows between COS components, it would also make sense to force https redirect on the Traefik ingress to enforce TLS everywhere.
According to the [Trafik charm documentation](https://charmhub.io/traefik-k8s/docs/https-redir), this can be achieved by modifying the require's charm code.
This request is to have each COS charm that integrates with Traefik ingress, expose a config option to force https redirect.

**Comment by mmkay** [comment]
We already have this; it's up to each charm author to define HTTP->HTTPS redirection. We surely have it in [prometheus](https://github.com/canonical/prometheus-k8s-operator/blob/main/src/charm.py#L176), [grafana](https://github.com/canonical/grafana-k8s-operator/blob/main/src/charm.py#L1330).

Is it what you were asking for? Closing this for now but please feel free to reopen if you think it's not answering your proposal.

**Comment by baycarbone** [comment]
Thanks for the feedback.
Could the redirection be implemented in all charms integrated with Traefik as part of the COS bundle if not already done?
As we deploy COS as one solution, it would not make sense to secure some endpoints but not all.

**Comment by PietroPasotti** [comment]
What we're saying is that we think that it already is the case. Are you asking because you think it isn't?

**Comment by baycarbone** [comment]
Ok I see. I believe it was not the case back when I opened the issue originally but perhaps this is no longer true. I would need to find time to test and confirm.

**Comment by PietroPasotti** [comment]
If you find a charm that does not automatically redirect to https, that's a bug for the specific charm, not the bundle as a whole.

**Comment by baycarbone** [comment]
Is it there for the catalogue charm? I see something about redirect in the ingress lib, but is this setting exposed to the user in order to enable redirect?
https://github.com/canonical/catalogue-k8s-operator/blob/5e5b275a51b0116e4298cd423c7aacd07c21ee1d/charm/lib/charms/traefik_k8s/v2/ingress.py#L245

**Comment by PietroPasotti** [comment]
it is exposed to the charm using the library, yes. It's not exposed to the admin using the charm though, unless the charm adds a config option for it (which we do not, as we don't see (yet) a use case for letting the cloud admin toggle it).

[You're right, catalogue doesn't force https.](https://github.com/canonical/catalogue-k8s-operator/blob/main/charm/src/charm.py#L69) I guess we thought it wasn't relevant as catalogue is a rather bare facade? Or perhaps it's an oversight, will double check with @simskij

**Comment by simskij** [comment]
Yes, catalogue is rather stupid (zero interaction capabilities), so we didn't bother implementing it there. It would probably be easy enough to fix though.

**Comment by PietroPasotti** [comment]
are you satisfied @baycarbone?

**Comment by baycarbone** [comment]
All good for me. Do you need me to open an issue against the catalogue charm or will you handle it?

**Comment by baycarbone** [comment]
Ok will do.
I agree from a technical point of view it does not seem necessary but if you look at the solution as a whole, having https redirect also for catalogue will avoid uncomfortable discussions with a customer's security team trying to explain why we have one endpoint that is still accessible over HTTP (even if it's just a frontend to the real app UIs).

**Comment by baycarbone** [comment]
One more question, instead of having a config option, could we have the same behavior as the other COS charms where the https redirect seems to be applied implicitly when using the TLS overlay.
