### ISSUE TITLE
Scrape metrics from kubernetes nodes and container runtime

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/cos-lite-bundle#33]
### Enhancement Proposal

Given the COS is a kubernetes bundle, it think I'd be a really nice addition to discover and scrape all the [kubernetes components](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/) without the need of manual configuration and also nodes and pods, although the latter would probably require another charm to be deployed along the current charms in the bundle.

Also, adding grafana dashboards for these metrics could come in handy too.

Thank you!

**Comment by simskij** [comment]
I agree with you. We've previously discussed this and it is really a two-part proposal.

1. We need to be able to collect telemetry for CK8s. This is likely to be solved using the planned `grafana-agent` machine charm, which among other things include `node_exporter`.
2. We need to be able to collect telemetry for MicroK8s. This is likely to be solved using a proxy charm and a telemetry plugin that will deploy `node_exporter, `kubestate-metrics`, and the kubernetes metrics server .

**Comment by simskij** [comment]
This will be addressed by the K8s team. Closing this issue as it is a no-op on our side.
