### ISSUE TITLE
Add itest: all metric names used in alert rules are in fact served by the workload

### ISSUE THREAD

**Issue by sed-i** [canonical/cos-lite-bundle#47]
### Enhancement Proposal

Iiuc, if any metric of an `expr` is missing, the alert wouldn't fire.
This may happen when the workload is updated with a breaking change which removes/renames metrics.

Before releasing a charm, it could be handy to verify that alerts would in fact evaluate. This is relevant for:
- alerts updated by the PR
- the charm's oci image resource is updated to workload version with a breaking change which removes/renames metrics

Related: https://github.com/canonical/cos-tool/issues/3

**Comment by simskij** [comment]
This is not something we'll be doing right now as it will introduce a lot of generated alert rules the administrator/operator might not want. We might in the future consider doing this using a manifest, or by allowing cos-tool to check a directory of alert rules against a metrics endpoint for compliance.
