### ISSUE TITLE
Add integration test prom-loki-traefik 

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/cos-lite-bundle#49]
### Enhancement Proposal

We should have an integration test as described in [this Prometheus PR](https://github.com/canonical/prometheus-k8s-operator/pull/397):

- Deploy prometheus, loki and traefik
- Relate prometheus and loki
  - Check that loki scrape job in prometheus config use internal IP or a FQDN
- Relate loki and traefik
  - Check that loki scrape job in prometheus config use external URL provided by traefik.
- Remove the relation between loki and traefik
  - Check that loki scrape job in prometheus config use internal IP or a FQDN again

**Comment by Abuelodelanada** [comment]
> I used to have one in Traefik, but I reverted to using tester charms instead of the 'real upstreams' because the bundle was unstable back then. Still we might be able to dig up some code from the traefik repo

I think those itest in traefik are great and should continue there.

I'm thinking that since the bundle is `stable` now we should test these kind of features here with real charms too... perhaps it's a little bit redundant but it is not harmful ;-)

**Comment by PietroPasotti** [comment]
I was proposing to copy the 'old tests' I had in traefik (which are no longer there), the ones using the real bundle charms, and use them as starting point for some bundle-wide integration testing here. 
I totally agree that we should do it :)

**Comment by Abuelodelanada** [comment]
Oh! I thought the tests were still there (I'm still asleep today)... Yes, we agree!
