### ISSUE TITLE
Update Bundle Readme

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/cos-lite-bundle#54]
### Enhancement Proposal

Document Traefik and Catalogue as part of the cos-lite bundle.

The cos-lite bundle readme makes no mention of Traefik or Catalogue.

Additionally, it seems as though Traefik needs an additional charm gateway configuration that is not mentioned.

**Comment by sed-i** [comment]
Thanks for pointing this out @jamesbeedy!
Please feel free to review #53.
