### ISSUE TITLE
Integration tests for TLS

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/cos-lite-bundle#78]
### Enhancement Proposal

A integration (scenario?) test suite for TLS is needed to test whether TLS is enabled or not between COS components

**Comment by sed-i** [comment]
Yep. Should probably add an overlay yaml with our stand-in CA.
Perhaps even parametrize the deployment so we run the same tests with and without TLS.

**Comment by PietroPasotti** [comment]
> Yep. Should probably add an overlay yaml with our stand-in CA. Perhaps even parametrize the deployment so we run the same tests with and without TLS.

oh that's a cool one
