### ISSUE TITLE
Use juju-bundle to simplify testing logic

### ISSUE THREAD

**Issue by sed-i** [canonical/cos-lite-bundle#8]
[juju-bundle](https://snapcraft.io/juju-bundle) is a bundle management plugin for juju maintained by @knkski.

> a juju plugin is any executable binary in $PATH that has the name juju-*, you can call it as juju foo instead of juju-foo so they're called plugins, but really it's just a convenience bit of functionality, instead of being a plugin to juju itself

> most of the kubeflow CI/CD uses it, because it handles stuff like filling in default resources. Here's a couple of examples:
> https://github.com/canonical/kfp-operators/blob/master/.github/workflows/integrate.yaml#L65
> https://github.com/canonical/kfp-operators/blob/master/.github/workflows/publish.yaml#L29-L32
> https://github.com/canonical/bundle-kubeflow/blob/master/.github/workflows/publish.yaml#L34-L36

> If you were to create a charms directory at the root of this repo and create a symlink inside for each charm with e.g. `ln -s ../../prometheus-operator prometheus`, you could run juju bundle deploy --build to have each charm built and deployed as part of the bundle. Does that meet your needs vs a bundle template? Otherwise, I'd be interesting in see if juju-bundle could be expanded to meet any extra needs.

> I've updated the juju-bundle plugin to handle these four use cases:
> ```shell
> juju bundle deploy                           # Don't build anything
> juju bundle deploy --build                   # Build every app with a source
> juju bundle deploy --build foo bar           # Build both `foo` and `bar` from their sources
> juju bundle deploy --build foo bar=../bar    # Build `foo` from its source, and build `bar` with a source of `../bar`
> ```
> 
> it also has a few other features, e.g. instead of using {%- if testing %} to include the avalanche app, you can just include it and use juju bundle deploy --exclude avalanche when you don't want to include it

> you could run `juju bundle deploy -b /tmp/RANDOM/bundle.yaml --build alertmanager=../`
> the juju-bundle plugin would then go off and build alertmanager only, save an updated bundle.yaml to a tempfile 
> --- @knkski 

So with juju-bundle the tests may looks like this:

Alertmanager integration tests:
1. alertmanager tox command downloads lma bundle
1. alertmanager tox command calls `juju bundle deploy -b /path/to/lma/bundle.yaml --build alertmanager={toxinidir}`
1. alertmanager tox command calls pytest on lma bundle (same as now)
1. lma test runs tests but does not build anything, only deploys the bundle

lma bundle integration tests:
1. lma bundle tox command calls `juju bundle deploy -b /path/to/lma/bundle.yaml`
1. lma bundle tox command calls pytest (same as now but do not build anything)

**Comment by simskij** [comment]
Juju bundle is deprecated and unmaintained, and we should look to replace it rather than adopt it. 😅
