### ISSUE TITLE
Document external dependencies for COS lite

### ISSUE THREAD

**Issue by peppepetra** [canonical/cos-lite-bundle#85]
### Bug Description

We need a list of external dependencies needed to have COS installed and working correctly.

This is mostly needed to communicate to customer how to configure proxy/firewall to allow COS setup.

Ideally this should include also dependencies that are not directly from components in the cos-lite bundle, but still they are core ones of a COS deployment like grafana-agent.

### To Reproduce

Not applicable

### Environment

Not applicable

### Relevant log output

```shell
Not applicable
```

**Comment by peppepetra** [comment]
We have one customer reporting grafana-agent trying to talk with Google Cloud and we are unsure what this traffic is for.

**Comment by dstathis** [comment]
I'm not exactly sure what you mean by external dependencies. As far as I can tell the answer is none. Can you give an example?

Note: For grafana-agent talking to google cloud, we expect that it is sending some telemetry home and we are looking in to it.

**Comment by simskij** [comment]
We should add a juju config toggle to allow opting out from sending telemetry, with the default being to send it.

**Comment by simskij** [comment]
Documentation will need to include egress requirements for things like:
- Charmhub
- Dockerhub
- Juju registry
- Snapcraft
- Github (Promtail?)

**Comment by lucabello** [comment]
The dependencies have been documented, both in the individual charms, and summarized [here](https://charmhub.io/topics/canonical-observability-stack/reference/best-practices#heading--egress).
