### ISSUE TITLE
Support use of certificates provided by third parties

### ISSUE THREAD

**Issue by przemeklal** [canonical/cos-lite-bundle#98]
### Enhancement Proposal

Hi,

Currently, the TLS overlay relies on the self-signed certificates charm. To use COS in production, however, we need to be able to use certificates provided by ANY third party. The use of charms that rely on "Let's Encrypt" (e.g. https://charmhub.io/route53-acme-operator) is not a solution since there are organizations that will require the use of certificates signed by their own Certificate Authorities or will use external CAs (such as DigiCert or GlobalSign to name a few).

Currently, such a scenario does not seem to be supported or at least it's not documented.

A good start would be an example of how to use a wildcard certificate in COS.

**Comment by sed-i** [comment]
We will address this only from the traefik side at this point. Closing.
